import "./globals.css";
import { ThemeProvider } from "../../components/theme/theme-provider";
import { ReactNode } from "react";

export const metadata = {
  title: "OpenMarket",
  description: "Generated by create next app",
};

interface LocaleLayoutProps {
  children: ReactNode;
  params: {
    locale: string;
  };
}

export default function LocaleLayout({
  children,
  params: { locale },
}: LocaleLayoutProps) {
  console.log(locale);
  return (
    <html lang={locale} suppressHydrationWarning>
      <body className="flex flex-col min-h-screen">
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
