import "./globals.css";
import { ThemeProvider } from "../../components/theme/theme-provider";
import { ReactNode } from "react";
import { unstable_setRequestLocale } from "next-intl/server";
import { UserProvider } from "@auth0/nextjs-auth0/client";

export const metadata = {
  title: "OpenMarket",
  description: "Generated by create next app",
};

interface LocaleLayoutProps {
  children: ReactNode;
  params: {
    locale: string;
  };
}

export default function LocaleLayout({
  children,
  params: { locale },
}: LocaleLayoutProps) {
  unstable_setRequestLocale(locale);

  return (
    <html lang={locale} suppressHydrationWarning>
      <UserProvider>
        <body className="flex flex-col min-h-screen">
          <ThemeProvider>{children}</ThemeProvider>
        </body>
      </UserProvider>
    </html>
  );
}
