import React, { ReactNode } from "react";

interface Metadata {
  title: string;
  description: string;
}

export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

interface RootLayoutProps {
  children: ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return <>{children}</>;
};

export default RootLayout;
